// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LogToFile.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace LogToFile.Context
{
    public class CourseDayConfiguration : IEntityTypeConfiguration<CourseDay>
    {
        public void Configure(EntityTypeBuilder<CourseDay> entity)
        {
            entity.ToTable("CourseDay");

            entity.Property(e => e.Offered).HasDefaultValueSql("((0))");

            entity.HasOne(d => d.DayIndexNavigation)
                .WithMany(p => p.CourseDays)
                .HasForeignKey(d => d.DayIndex)
                .HasConstraintName("FK_CourseDay_WeekDay");
        }
    }
}
