// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LogToFile.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace LogToFile.Context
{
    public class CourseInstructorConfiguration : IEntityTypeConfiguration<CourseInstructor>
    {
        public void Configure(EntityTypeBuilder<CourseInstructor> entity)
        {
            entity.HasKey(e => new { e.CourseID, e.PersonID });

            entity.ToTable("CourseInstructor");

            entity.HasOne(d => d.Course)
                .WithMany(p => p.CourseInstructors)
                .HasForeignKey(d => d.CourseID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CourseInstructor_Course");

            entity.HasOne(d => d.Person)
                .WithMany(p => p.CourseInstructors)
                .HasForeignKey(d => d.PersonID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CourseInstructor_Person");
        }
    }
}
