// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LogToFile.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace LogToFile.Context
{
    public class OfficeAssignmentConfiguration : IEntityTypeConfiguration<OfficeAssignment>
    {
        public void Configure(EntityTypeBuilder<OfficeAssignment> entity)
        {
            entity.HasKey(e => e.InstructorID);

            entity.ToTable("OfficeAssignment");

            entity.Property(e => e.InstructorID).ValueGeneratedNever();

            entity.Property(e => e.Location)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Timestamp)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.HasOne(d => d.Instructor)
                .WithOne(p => p.OfficeAssignment)
                .HasForeignKey<OfficeAssignment>(d => d.InstructorID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OfficeAssignment_Person");
        }
    }
}
