// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LogToFile.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace LogToFile.Context
{
    public class OnlineCourseConfiguration : IEntityTypeConfiguration<OnlineCourse>
    {
        public void Configure(EntityTypeBuilder<OnlineCourse> entity)
        {
            entity.HasKey(e => e.CourseID);

            entity.ToTable("OnlineCourse");

            entity.Property(e => e.CourseID).ValueGeneratedNever();

            entity.Property(e => e.URL)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Course)
                .WithOne(p => p.OnlineCourse)
                .HasForeignKey<OnlineCourse>(d => d.CourseID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OnlineCourse_Course");
        }
    }
}
