// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LogToFile.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace LogToFile.Context
{
    public class StudentGradeConfiguration : IEntityTypeConfiguration<StudentGrade>
    {
        public void Configure(EntityTypeBuilder<StudentGrade> entity)
        {
            entity.HasKey(e => e.EnrollmentID);

            entity.ToTable("StudentGrade");

            entity.Property(e => e.Grade)
                .HasColumnType("decimal(3, 2)")
                .HasAnnotation("Relational:ColumnType", "decimal(3, 2)");

            entity.HasOne(d => d.Course)
                .WithMany(p => p.StudentGrades)
                .HasForeignKey(d => d.CourseID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentGrade_Course");

            entity.HasOne(d => d.Student)
                .WithMany(p => p.StudentGrades)
                .HasForeignKey(d => d.StudentID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentGrade_Student");
        }
    }
}
