// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LogToFile.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace LogToFile.Context
{
    public class WeekDayNameConfiguration : IEntityTypeConfiguration<WeekDayName>
    {
        public void Configure(EntityTypeBuilder<WeekDayName> entity)
        {
            entity.HasKey(e => e.WeekId)
                .HasName("PK_WeekDay");

            entity.ToTable("WeekDayName");

            entity.Property(e => e.DayName).IsRequired();
        }
    }
}
