// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EntityCore_csharp.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace EntityCore_csharp.Context
{
    public class CategoryConfiguration : IEntityTypeConfiguration<Category>
    {
        public void Configure(EntityTypeBuilder<Category> entity)
        {
            entity.Property(e => e.CategoryId)
                .HasColumnName("CategoryID")
                .HasComment("Primary key");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(15);

            entity.Property(e => e.Description)
                .HasColumnType("ntext")
                .HasAnnotation("Relational:ColumnType", "ntext");

            entity.Property(e => e.Picture)
                .HasColumnType("image")
                .HasAnnotation("Relational:ColumnType", "image");
        }
    }
}
