// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Oracle1.Models
{
    public partial class HelpMessage
    {
        public decimal Id { get; set; }
        public string MsgDescr { get; set; }
        public string MsgBody { get; set; }
        public string LanguageCode { get; set; }
    }
}