// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Oracle1.Models
{
    public partial class OcsMessage
    {
        public decimal Id { get; set; }
        public string ActiveFlag { get; set; }
        public string OcsDbFieldName { get; set; }
        public string OcsFormFieldName { get; set; }
        public int? OcsFormFieldOrder { get; set; }
        public string OcsLangCode { get; set; }
        public string OcsMainFrameMatch { get; set; }
        public string OcsMessageTxt { get; set; }
        public string OcsMessageTypeCode { get; set; }
        public string OcsmsgcdCode { get; set; }
        public string OcsRequiredFlag { get; set; }
        public string OcsTemplateName { get; set; }
        public string OcsTemplateTitle { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string OcsFormFieldType { get; set; }
        public string OcsScreenName { get; set; }
        public string CorrectAnswerFlag { get; set; }
    }
}