// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LogToFile.Models
{
    public partial class CourseInstructor
    {
        public int CourseID { get; set; }
        public int PersonID { get; set; }

        public virtual Course Course { get; set; }
        public virtual Person Person { get; set; }
    }
}