// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;

#nullable disable

namespace WorkingWithJson1.Models
{
    public partial class Person
    {
        private string _addressJson;
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public IList<Address> Addresses { get; set; }

        [NotMapped]
        public string AddressJson
        {
            get
            {
                return JsonConvert.SerializeObject(Addresses);
            }
        }
    }
}