// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EntityCore_csharp.Models
{
    public partial class BusinessEntityPhone
    {
        public int BusinessEntityPhoneId { get; set; }
        /// <summary>
        /// Phone number
        /// </summary>
        public string PhoneNumber { get; set; }
        public int? PhoneNumberTypeId { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}