// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EntityCore_csharp.Models
{
    public partial class Contact
    {
        public Contact()
        {
            ContactDevices = new HashSet<ContactDevice>();
            Customers = new HashSet<Customer>();
        }

        /// <summary>
        /// Id
        /// </summary>
        public int ContactId { get; set; }
        /// <summary>
        /// First name
        /// </summary>
        public string FirstName { get; set; }
        /// <summary>
        /// Last name
        /// </summary>
        public string LastName { get; set; }
        /// <summary>
        /// Contact Type Id
        /// </summary>
        public int? ContactTypeIdentifier { get; set; }

        public virtual ContactType ContactTypeIdentifierNavigation { get; set; }
        public virtual ICollection<ContactDevice> ContactDevices { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}