// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace StoredProcedureInsertNewCategory.Models
{
    public partial class uspGenerateClassResult
    {
        public string Col0 { get; set; }
    }
}
