// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.IO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Oracle1.Models;

namespace Oracle1.Context
{
    public partial class ProjectContext : DbContext
    {
        public ProjectContext()
        {
        }

        public ProjectContext(DbContextOptions<ProjectContext> options)
            : base(options)
        {
        }

        public virtual DbSet<HelpMessage> HelpMessages { get; set; }
        public virtual DbSet<OcsMessage> OcsMessages { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {

                optionsBuilder.UseOracle(File.ReadAllText(@"C:\OED\Dotnetland\OracleConnectionStrings\devConnection.txt"));

            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:DefaultSchema", "OCS");

            modelBuilder.Entity<HelpMessage>(entity =>
            {
                entity.ToTable("HELP_MESSAGES");

                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .HasColumnType("NUMBER");

                entity.Property(e => e.LanguageCode)
                    .HasColumnName("LANGUAGE_CODE")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.MsgBody)
                    .HasColumnName("MSG_BODY")
                    .HasMaxLength(2000)
                    .IsUnicode(false);

                entity.Property(e => e.MsgDescr)
                    .HasColumnName("MSG_DESCR")
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<OcsMessage>(entity =>
            {
                entity.ToTable("OCS_MESSAGES");

                entity.HasIndex(e => e.OcsmsgcdCode)
                    .HasName("OCSMSG_OCSMSGCD_FK_I");

                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .HasColumnType("NUMBER");

                entity.Property(e => e.ActiveFlag)
                    .HasColumnName("ACTIVE_FLAG")
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.CorrectAnswerFlag)
                    .HasColumnName("CORRECT_ANSWER_FLAG")
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.EndDate)
                    .HasColumnName("END_DATE")
                    .HasColumnType("DATE");

                entity.Property(e => e.OcsDbFieldName)
                    .HasColumnName("OCS_DB_FIELD_NAME")
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.OcsFormFieldName)
                    .HasColumnName("OCS_FORM_FIELD_NAME")
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.OcsFormFieldOrder).HasColumnName("OCS_FORM_FIELD_ORDER");

                entity.Property(e => e.OcsFormFieldType)
                    .HasColumnName("OCS_FORM_FIELD_TYPE")
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.OcsLangCode)
                    .HasColumnName("OCS_LANG_CODE")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.OcsMainFrameMatch)
                    .HasColumnName("OCS_MAIN_FRAME_MATCH")
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.OcsMessageTxt)
                    .HasColumnName("OCS_MESSAGE_TXT")
                    .HasMaxLength(2000)
                    .IsUnicode(false);

                entity.Property(e => e.OcsMessageTypeCode)
                    .HasColumnName("OCS_MESSAGE_TYPE_CODE")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.OcsRequiredFlag)
                    .HasColumnName("OCS_REQUIRED_FLAG")
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasDefaultValueSql(@"'N'
 ");

                entity.Property(e => e.OcsScreenName)
                    .HasColumnName("OCS_SCREEN_NAME")
                    .HasMaxLength(45)
                    .IsUnicode(false);

                entity.Property(e => e.OcsTemplateName)
                    .HasColumnName("OCS_TEMPLATE_NAME")
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.OcsTemplateTitle)
                    .HasColumnName("OCS_TEMPLATE_TITLE")
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.OcsmsgcdCode)
                    .IsRequired()
                    .HasColumnName("OCSMSGCD_CODE")
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.StartDate)
                    .HasColumnName("START_DATE")
                    .HasColumnType("DATE");
            });

            modelBuilder.HasSequence("CLMADDRCHG_SEQ");

            modelBuilder.HasSequence("CLMADDRVER_SEQ");

            modelBuilder.HasSequence("CLMINFOGGL_SEQ");

            modelBuilder.HasSequence("CLMPINRES_SEQ");

            modelBuilder.HasSequence("CLMPINRESA_SEQ");

            modelBuilder.HasSequence("CLMPINTGGL_SEQ");

            modelBuilder.HasSequence("CLMTEMLADD_SEQ");

            modelBuilder.HasSequence("EBWRKSRCH_SEQ");

            modelBuilder.HasSequence("EPIQLWACERT_SEQ");

            modelBuilder.HasSequence("ICCHG_SEQ");

            modelBuilder.HasSequence("ICCTRANS_SEQ");

            modelBuilder.HasSequence("ICCTRCMMTS_SEQ");

            modelBuilder.HasSequence("ICEMP_SEQ");

            modelBuilder.HasSequence("ICRANDEMP_SEQ");

            modelBuilder.HasSequence("ICRET_SEQ");

            modelBuilder.HasSequence("ICSELFEMP_SEQ");

            modelBuilder.HasSequence("ICSTATE_SEQ");

            modelBuilder.HasSequence("ICSTFNOTE_SEQ");

            modelBuilder.HasSequence("ICSTUD_SEQ");

            modelBuilder.HasSequence("ICSTUDSCH_SEQ");

            modelBuilder.HasSequence("ICSTUDWRKS_SEQ");

            modelBuilder.HasSequence("ICTRANAUD_SEQ");

            modelBuilder.HasSequence("ICTRANCB_SEQ");

            modelBuilder.HasSequence("IMAPPSAF_SEQ");

            modelBuilder.HasSequence("INSDOCTPCD_SEQ");

            modelBuilder.HasSequence("LOGINTR_SEQ");

            modelBuilder.HasSequence("LOGTRAN_SEQ");

            modelBuilder.HasSequence("LOGTRANAPP_SEQ");

            modelBuilder.HasSequence("LWAOP_SEQ");

            modelBuilder.HasSequence("MAST5TTDIM_SEQ");

            modelBuilder.HasSequence("MENUTRAN_SEQ");

            modelBuilder.HasSequence("OCSEBTRAN_SEQ");

            modelBuilder.HasSequence("OCSERR_SEQ");

            modelBuilder.HasSequence("OCSEXTBENTRN_SEQ");

            modelBuilder.HasSequence("OCSLFTRAN_SEQ");

            modelBuilder.HasSequence("OCSMSG_SEQ");

            modelBuilder.HasSequence("OCSPATH_SEQ");

            modelBuilder.HasSequence("OCSREPAYDC_SEQ");

            modelBuilder.HasSequence("OCSREPAYTR_SEQ");

            modelBuilder.HasSequence("OCSWSOUSGCNT_SEQ");

            modelBuilder.HasSequence("PINCHG_SEQ");

            modelBuilder.HasSequence("PUADLYFIL_SEQ");

            modelBuilder.HasSequence("PUAGGLSTAT_SEQ");

            modelBuilder.HasSequence("PUAICDET_SEQ");

            modelBuilder.HasSequence("PUAWKDET_SEQ");

            modelBuilder.HasSequence("QEMAILDOM_SEQ");

            modelBuilder.HasSequence("SECANS_SEQ");

            modelBuilder.HasSequence("SECQUES_SEQ");

            modelBuilder.HasSequence("SEPANS_SEQ");

            modelBuilder.HasSequence("SEPCLMSTAT_SEQ");

            modelBuilder.HasSequence("SEQUENCETEST_SEQUENCE");

            modelBuilder.HasSequence("SSAVERLOG_SEQ");

            modelBuilder.HasSequence("UIBRVWANS_SEQ");

            modelBuilder.HasSequence("UIDATES_SEQ");

            modelBuilder.HasSequence("WAGSSNTRK_SEQ");

            modelBuilder.HasSequence("WEBAPP_SEQ");

            modelBuilder.HasSequence("WEBLOG_SEQ");

            modelBuilder.HasSequence("WEBSYSOUT_SEQ");

            modelBuilder.HasSequence("WKSHRAUDIT_SEQ");

            modelBuilder.HasSequence("WKSHREMP_SEQ");

            modelBuilder.HasSequence("WKSHRPLN_SEQ");

            modelBuilder.HasSequence("WKSHRUNI_SEQ");

            modelBuilder.HasSequence("Y_DEPARTMENT_SEQUENCE");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}