// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConnectionConfiguration.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace ConnectionConfiguration.Context
{
    public class PersonConfiguration : IEntityTypeConfiguration<Person>
    {
        public void Configure(EntityTypeBuilder<Person> entity)
        {
            entity.ToTable("Person");

            entity.Property(e => e.Discriminator)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.EnrollmentDate)
                .HasColumnType("datetime")
                .HasAnnotation("Relational:ColumnType", "datetime");

            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.HireDate)
                .HasColumnType("datetime")
                .HasAnnotation("Relational:ColumnType", "datetime");

            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50);
        }
    }
}
